**Keras - Binary Classification on DDoS2007 file**

In [1]:
%matplotlib notebook 
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.utils.multiclass import unique_labels
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras import Sequential
from keras.layers import Dense
from keras import backend as K
import tensorflow as tf

tf.logging.set_verbosity(tf.logging.ERROR)

Using TensorFlow backend.

    Some functions to transform data or plot confusion matrix

In [2]:
def spounge(string):
   new = ['0' for i in range(43)]
   a = string
   l = a.split()
   for i in l:
     n = int(i.split(":")[0])
     if len(i) == 1:
        new[0] = str(n)
     else:
        new[n] = i.split(':')[1]
   return new

def plot_confusion_matrix(y_true, y_pred, classes,
                          normalize=True,
                          title=None,
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if not title:
        if normalize:
            title = 'Normalized confusion matrix'
        else:
            title = 'Confusion matrix, without normalization'

    # Compute confusion matrix
    cm = confusion_matrix(y_true, y_pred)
    # Only use the labels that appear in the data
    classes = classes[unique_labels(y_true, y_pred)]
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    fig, ax = plt.subplots()
    im = ax.imshow(cm, interpolation='nearest', cmap=cmap)
    ax.figure.colorbar(im, ax=ax)
    # We want to show all ticks...
    ax.set(xticks=np.arange(cm.shape[1]),
           yticks=np.arange(cm.shape[0]),
           # ... and label them with the respective list entries
           xticklabels=classes, yticklabels=classes,
           title=title,
           ylabel='True label',
           xlabel='Predicted label')

    # Rotate the tick labels and set their alignment.
    plt.setp(ax.get_xticklabels(), rotation=45, ha="right",
             rotation_mode="anchor")

    # Loop over data dimensions and create text annotations.
    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            ax.text(j, i, format(cm[i, j], fmt),
                    ha="center", va="center",
                    color="white" if cm[i, j] > thresh else "black")
    fig.tight_layout()
    return ax

    read file into dataframe

In [3]:
df = pd.read_csv('e:/dalhousie_spark/DDoS2007.csv', header = None)

    transformation dataframe into columns (each packet one column)

In [4]:
tmp = df.apply(lambda row: (spounge(row[0])),axis=1)
m = pd.DataFrame(tmp.tolist())
m = m.astype("int64")

In [5]:
m.astype('int64')

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,0,151997,36700,61996,0,37666,0,0,0,0,...,1,0,0,0,0,65535,5105,0,0,0
1,0,167737,197843,0,1649,0,1283,0,0,0,...,0,0,0,0,0,0,0,1069,0,4652
2,0,143541,153817,0,49747,0,1455,0,0,0,...,0,0,0,0,0,0,0,309,0,61584
3,0,197054,89048,55294,0,80,0,0,0,0,...,1,0,0,0,0,55853,42600,0,0,0
4,0,75724,99286,0,63946,0,9042,0,0,0,...,0,0,0,0,0,0,0,112,0,46019
5,0,112513,90369,61885,0,80,0,0,0,0,...,1,0,0,0,0,1024,16498,0,0,0
6,1,100670,212911,443,0,63191,0,0,0,0,...,1,0,0,0,0,2043,20123,0,0,0
7,1,122961,38919,80,0,57469,0,0,0,0,...,1,0,0,0,0,1320,8180,0,0,0
8,0,131153,101008,47686,0,53617,0,0,0,0,...,1,0,0,0,0,65535,59739,0,0,0
9,0,152150,100171,0,61514,0,18792,0,0,0,...,0,0,0,0,0,0,0,40,0,0
10,0,136373,217805,0,50404,0,1455,0,0,0,...,0,0,0,0,0,0,0,314,0,4449
11,0,157246,133340,0,8505,0,2049,0,0,0,...,0,0,0,0,0,0,0,131,0,19518
12,0,98864,157843,80,0,28635,0,0,0,0,...,1,0,0,0,0,19127,37668,0,0,0
13,0,148139,81113,0,123,0,7777,0,0,0,...,0,0,0,0,0,0,0,376,0,14927
14,1,166720,137185,0,56266,0,8080,0,0,0,...,0,0,0,0,0,0,0,1453,0,26894
15,1,184122,133746,14000,0,58772,0,0,0,0,...,1,1,0,0,0,501,36343,0,0,0
16,0,50990,139630,36607,0,3080,0,0,0,0,...,1,0,0,0,0,260,25623,0,0,0
17,0,168937,167958,41515,0,49701,0,0,0,0,...,1,0,0,0,0,16384,64674,0,0,0
18,0,131096,130349,1205,0,5121,0,0,0,0,...,1,1,0,0,0,64603,44053,0,0,0
19,0,139575,38636,80,0,52057,0,0,0,0,...,1,0,0,1,0,8190,22131,0,0,0
20,0,186216,115159,80,0,47503,0,0,0,0,...,1,0,0,0,0,269,25386,0,0,0
21,0,164577,119569,0,12345,0,32453,0,0,0,...,0,0,0,0,0,0,0,38,0,21865
22,1,157450,64775,80,0,52875,0,0,0,0,...,1,0,0,0,0,1320,5620,0,0,0
23,1,120114,187055,36071,0,443,0,0,0,0,...,1,0,0,0,1,3845,37076,0,0,0
24,0,119875,35958,8832,0,2746,0,0,0,0,...,1,0,0,0,0,17424,37434,0,0,0
25,0,83350,126277,2682,0,80,0,0,0,0,...,1,0,0,0,0,65535,3931,0,0,0
26,0,123668,144712,1541,0,80,0,0,0,0,...,1,0,0,0,0,65535,1039,0,0,0
27,0,93785,68218,44698,0,80,0,0,0,0,...,1,0,0,0,1,8104,24486,0,0,0
28,0,151266,165467,80,0,4858,0,0,0,0,...,1,0,0,0,0,8372,39857,0,0,0
29,0,93104,87549,61213,0,1935,0,0,0,0,...,1,1,0,0,0,258,60674,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999970,0,86534,98753,0,3496,0,16402,0,0,0,...,0,0,0,0,0,0,0,1283,0,61011
999971,1,154825,111365,443,0,50939,0,0,0,0,...,1,0,0,0,0,146176,3362,0,0,0
999972,1,71994,89778,0,123,0,37694,0,0,0,...,0,0,0,0,0,0,0,56,0,44811
999973,0,182240,172872,80,0,1212,0,0,0,0,...,1,0,0,0,0,6432,19616,0,0,0
999974,0,187428,96565,59603,0,15653,0,0,0,0,...,1,0,0,0,0,3953,23369,0,0,0
999975,0,131369,139727,0,9501,0,12014,0,0,0,...,0,0,0,0,0,0,0,89,0,55363
999976,0,183892,140300,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999977,0,99187,107125,80,0,44539,0,0,0,0,...,1,0,0,0,0,989,27186,0,0,0
999978,0,164120,126705,443,0,59415,0,0,0,0,...,1,0,0,0,0,65535,21768,0,0,0
999979,1,109717,156989,36345,0,80,0,0,0,0,...,1,0,0,0,0,8662,29133,0,0,0
999980,1,100670,140246,443,0,59196,0,0,0,0,...,1,0,0,0,0,1927,2684,0,0,0
999981,1,91071,143376,80,0,61437,0,0,0,0,...,1,0,0,0,0,1320,62008,0,0,0
999982,1,119972,214703,35718,0,443,0,0,0,0,...,1,1,0,0,0,9511,51932,0,0,0
999983,1,100670,140246,443,0,59196,0,0,0,0,...,1,0,0,0,0,1927,25489,0,0,0
999984,1,71243,132742,443,0,44863,0,0,0,0,...,1,0,0,0,0,2043,37046,0,0,0
999985,1,172228,155981,49351,0,443,0,0,0,0,...,1,0,0,0,0,32357,39166,0,0,0
999986,1,153761,140618,0,30409,0,53,0,0,0,...,0,0,0,0,0,0,0,65,0,49873
999987,1,97743,127292,56194,0,80,0,0,0,0,...,1,0,0,0,0,14490,27063,0,0,0
999988,1,91071,143376,80,0,61437,0,0,0,0,...,1,0,0,0,0,1320,28047,0,0,0
999989,1,71243,132742,443,0,44863,0,0,0,0,...,1,0,0,0,0,2043,48462,0,0,0
999990,1,153991,137348,443,0,53015,0,0,0,0,...,1,0,0,0,0,77,4302,0,0,0
999991,1,153991,137348,443,0,53015,0,0,0,0,...,1,1,0,0,0,77,52816,0,0,0
999992,0,147426,196495,80,0,47311,0,0,0,0,...,1,0,0,0,0,7672,33601,0,0,0
999993,0,159966,133197,80,0,13332,0,0,0,0,...,1,0,0,0,0,6577,44909,0,0,0
999994,0,119439,130257,0,62504,0,1485,0,0,0,...,0,0,0,0,0,0,0,1305,0,30764
999995,0,156105,133368,2867,0,80,0,0,0,0,...,1,0,0,0,0,65535,7428,0,0,0
999996,0,138466,134185,443,0,51745,0,0,0,0,...,1,1,0,0,0,17688,34707,0,0,0
999997,0,127470,74341,51246,0,80,0,0,0,0,...,1,0,0,0,0,16614,30004,0,0,0
999998,1,153991,137348,443,0,53015,0,0,0,0,...,1,0,0,0,0,77,32632,0,0,0
999999,1,104111,137419,443,0,50276,0,0,0,0,...,1,0,0,0,0,961,2066,0,0,0

In [6]:
m.head()

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,0,151997,36700,61996,0,37666,0,0,0,0,...,1,0,0,0,0,65535,5105,0,0,0
1,0,167737,197843,0,1649,0,1283,0,0,0,...,0,0,0,0,0,0,0,1069,0,4652
2,0,143541,153817,0,49747,0,1455,0,0,0,...,0,0,0,0,0,0,0,309,0,61584
3,0,197054,89048,55294,0,80,0,0,0,0,...,1,0,0,0,0,55853,42600,0,0,0
4,0,75724,99286,0,63946,0,9042,0,0,0,...,0,0,0,0,0,0,0,112,0,46019

    Dataset regularization and Split

In [7]:
# creating input columns and target column
X= m.iloc[:,1:42]
y= m.iloc[:,0]

 #regularizing the dataset (works better)
 #standardizing  input features

sc = StandardScaler()
X = sc.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

    The Network Model (42:128:128:1)

In [8]:
NN = Sequential()
NN.add(Dense(128, activation='relu', kernel_initializer='random_normal', input_dim=41))
NN.add(Dense(128, activation='relu', kernel_initializer='random_normal'))
NN.add(Dense(1, activation='sigmoid', kernel_initializer='random_normal'))

WARNING:tensorflow:From C:\Users\Manero\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

    Train and Fit

In [ ]:
NN.compile(optimizer ='adam',loss='binary_crossentropy', metrics =['accuracy'])
NN.summary()
#Fitting the data to the training dataset
NN.fit(X_train,y_train, batch_size=10, epochs=1)

eval_model=NN.evaluate(X_train, y_train)
print("model result: ",eval_model)

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              (None, 128)               5376
_________________________________________________________________
dense_2 (Dense)              (None, 128)               16512
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 129
=================================================================
Total params: 22,017
Trainable params: 22,017
Non-trainable params: 0
_________________________________________________________________
Epoch 1/1
700000/700000 [==============================] - 1156s 2ms/step - loss: 0.3369 - acc: 0.8470
390848/700000 [===============>..............] - ETA: 43s

    Final evaluation / Confusion Matrix

In [ ]:
y_pred = NN.predict(X_test)
y_pred =(y_pred>0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)

    Confusion Plots

In [ ]:
plot_confusion_matrix(y_test, y_pred, classes=np.array(['0','1']),
                          normalize=False,
                          title=None,
                          cmap=plt.cm.Blues)
plot_confusion_matrix(y_test, y_pred, classes=np.array(['0','1']),
                          normalize=True,
                          title=None,
                          cmap=plt.cm.Blues)